### ISSUE TITLE
Writing ratio position in Anchorage

### ISSUE THREAD

**Issue by webmaster128** [Raizlabs/Anchorage#35]
I want to position an element at 1/3 of the screen's Y axis, which works fine using

```
        NSLayoutConstraint(
            item: logo,
            attribute: .centerY,
            relatedBy: .equal,
            toItem: self,
            attribute: .bottom,
            multiplier: 0.333,
            constant: 0.0).isActive = true
```

Is it possible to write this constraint in Anchorage syntax? I tried `logo.centerYAnchor == bottomAnchor * 1 / 3` and `logo.centerYAnchor == 0.333 * bottomAnchor` but both result in compile errors.

**Comment by jvisenti** [comment]
Anchorage is built on top of the `NSLayoutAnchor` API, which only supports multipliers for `NSLayoutDimension`s, and not for `NSLayoutXAxisAnchor` or `NSLayoutYAxisAnchor` 😞 

It would probably be a fair bit of work to provide an API in Anchorage that wraps a raw `NSLayoutConstraint` cleanly rather than using anchors, but if it's something you'd like to see in the library then a PR is welcome 🙂

**Comment by webmaster128** [comment]
Okay thanks. It's not a priority right now but it might be as soon as we use Anchorage is larger parts of the project.

**Comment by jvisenti** [comment]
Closing this for now. Currently Anchorage uses only the NSLayoutAnchor API, which doesn't support multipliers in anything but NSLayoutDimension constraints
