### ISSUE TITLE
Question: If I remove the constraint and change the property, do I need to add again?

### ISSUE THREAD

**Issue by cikpis** [Raizlabs/Anchorage#43]
Hey guys, I have one question. Having this code:
```swift
viewTopAnchor = (view_1.topAnchor = view_2.topAnchor)
```

then at some point I need to updated the viewTopAnchor property
```swift
removeConstraint(viewTopAnchor)
viewTopAnchor = (view_1.topAnchor = view_3.bottomAnchor)
addConstraint(viewTopAnchor) // is this optional or mandatory after removeConstraint?
```

The question is, due to the Anchorage is adding automatically the constraint when you declare it, should I add it manually if I remove and redeclare it again? Because seems that is I don't add it manually the view is broken.

**Comment by ZevEisenberg** [comment]
The `==` operator (along with `>=` and `<=`) activates the constraints that it returns, so there should never be any need to call `addConstraint(...)`. You can also call `viewTooAnchor.isActive = false` instead of removing it, but either one should work. The nice thing about just deactivating it is that you don't have to keep track of which view it was added to.

As for your view being broken, can you confirm whether the new constraint is being added correctly, perhaps by using the debugger or view hierarchy debugger? Are you in a situation where you might need to explicitly force a layout pass with `layoutIfNeeded()`?

**Comment by ZevEisenberg** [comment]
The `==` operator (along with `>=` and `<=`) activates the constraints that it returns, so there should never be any need to call `addConstraint(...)`. You can also call `viewTooAnchor.isActive = false` instead of removing it, but either one should work. The nice thing about just deactivating it is that you don't have to keep track of which view it was added to.

As for your view being broken, can you confirm whether the new constraint is being added correctly, perhaps by using the debugger or view hierarchy debugger? Are you in a situation where you might need to explicitly force a layout pass with `layoutIfNeeded()`?

**Comment by cikpis** [comment]
```swift
func playDeleteButtonToPreposition(sender: ListSelectionButton) {
    removeConstraint(sender.constrainstLeft)
    sender.constrainstLeft = (sender.leftAnchor == leftAnchor)
    addConstraint(sender.constrainstLeft)
    layoutIfNeeded()
}
```
If I don't call `addConstraint(sender.constrainstLeft)` he view is broken. 

Btw, if I set isActive but at the end I need to set different constraint can I do it? Like:
```swift
sender.constrainstLeft.isActive = false
sender.constrainstLeft = (sender.leftAnchor == leftAnchor)
sender.constrainstLeft.isActive = true
```
Is this correct?

**Comment by jvisenti** [comment]
Anchorage returns active constraints by default, so there's no need set `isActive = true`. Have you tried simply
```
func playDeleteButtonToPreposition(sender: ListSelectionButton) {
    sender.constrainstLeft.isActive = false
    sender.constrainstLeft = (sender.leftAnchor == leftAnchor)
}
```

**Comment by cikpis** [comment]
I tried and is not working.

**Comment by ZevEisenberg** [comment]
@cikpis your code looks right, so sounds like it's a bug in either Anchorage or somewhere else in your code. Could you please try this to help narrow it down by replacing the Anchorage code with the equivalent layout anchor code, and seeing if the problem persists:

```swift
func playDeleteButtonToPreposition(sender: ListSelectionButton) {
    sender.constrainstLeft.isActive = false
    sender.translatesAutoresizingMaskIntoConstraints = false // Anchorage normally does this for you
    sender.constraintsLeft = sender.leftAnchor.constraint(equalTo: leftAnchor)
    sender.constraintsLeft.isActive = true
    layoutIfNeeded()
}
```

Let us know how it goes!

**Comment by cikpis** [comment]
@ZevEisenberg that is the point. I was using the native one before changing to Anchorage and all was working properly :)

I'll check deeply in order to understand the problem. The funny thing is that in another class your library is working like expected. For that I asked if the constraints need to be added again after I remove them. 
Anyway, I'll keep you posted.

**Comment by jvisenti** [comment]
Closing this for now until there's more info
